instance:
  resources:
    data:
      limits:
        cpu: "6"
        memory: 6Gi
      requests:
        cpu: "5"
        memory: 5Gi
    metrics:
      limits:
        cpu: 750m
        memory: 750Mi
      requests:
        cpu: 650m
        memory: 650Mi
